# Generated by Django 5.1.1 on 2026-01-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
